<?php

function simplify_content_types_form_alter(&$form, &$form_state, $form_id) {
    print '<pre>';
    print_r($form);
    print '</pre>';
    if ($form_id === 'tips_and_tricks_node_form') {
        $form['path']['#access'] = 0;
    }
    if ($form_id === 'awards_node_form' && $form['uid']['#value'] !== 1) {
        $form['comment_settings']['comment']['#default_value'] = 1;
        $form['comment_settings']['#access'] = 0;
    }
}
